# Generated by Django 2.2 on 2021-08-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='in_staff',
            new_name='is_staff',
        ),
    ]
